/*
================================================================================
  CONSUMER SHOPPING TRENDS — EXPLORATORY DATA ANALYSIS
================================================================================
  Author:      Namit
  Platform:    Microsoft SQL Server (T-SQL)
  Source data: cleaned_customer_trend.csv (3,900 rows), cleaned and exported
               from Python/pandas — see companion notebook:
               Consumer_Shopping_Trend_Analysis.ipynb 
  OBJECTIVE
  ---------
  This script explores retail transaction data to answer business-relevant
  questions about revenue drivers, customer segments, product performance,
  and purchase behavior. It's organized into four sections:
 
      1. Revenue & Spending Patterns
      2. Product & Category Performance
      3. Customer Segmentation & Loyalty
      4. Behavioral & Cross-Factor Analysis
 
  Each query is preceded by the business question it answers and a short
  note on why that framing was chosen. Column names match the cleaned
  dataset (snake_case, e.g. purchase_amount_usd, not "Purchase Amount (USD)").
================================================================================
*/
 
 
/* ============================================================================
   SECTION 1: REVENUE & SPENDING PATTERNS
   ============================================================================
   These queries look at where revenue comes from and how spending varies
   across simple customer and order-level attributes.
*/
 
-- Q1. What is the total revenue generated by male vs. female customers?
-- Basic revenue split by gender — a starting point for any demographic
-- targeting discussion.
SELECT gender,
       SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY gender;
 
 
-- Q2. Which customers used a discount but still spent more than the
-- average purchase amount?
-- Identifies customers who aren't purely price-sensitive — they took a
-- discount when offered, but it wasn't the only thing driving their spend.
-- Useful for spotting high-value customers who'd respond well to targeted
-- promotions without needing to discount as deeply.
SELECT customer_id,
       purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer);
 
 
-- Q3. Compare the average purchase amount between Standard and Express
-- shipping.
-- Tests whether customers who pay for faster shipping also tend to spend
-- more per order — a signal for whether shipping speed correlates with
-- basket size or customer willingness to pay.
SELECT shipping_type,
       ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
 
 
-- Q4. What is the revenue contribution of each age group?
-- Uses the age_group feature engineered in the cleaning notebook
-- (young_adult / adult / middle_aged / senior) to see which age cohort
-- drives the most total revenue — informs where marketing spend has the
-- biggest ceiling.
SELECT age_group,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
 
 
-- Q5. Which 10 locations generate the highest average revenue
-- per customer?
-- Total revenue by location can just reflect population size (more
-- customers = more revenue). Averaging per customer instead controls for
-- that, surfacing locations with genuinely higher-value customers rather
-- than just higher customer counts.
SELECT TOP 10
       location,
       COUNT(customer_id)                       AS customer_count,
       ROUND(AVG(purchase_amount_usd), 2)        AS avg_revenue_per_customer,
       SUM(purchase_amount_usd)                  AS total_revenue
FROM customer
GROUP BY location
ORDER BY avg_revenue_per_customer DESC;
 
 
/* ============================================================================
   SECTION 2: PRODUCT & CATEGORY PERFORMANCE
   ============================================================================
   These queries evaluate products and categories on rating, discounting,
   and sales volume, both overall and within category.
*/
 
-- Q6. Which are the top 5 products with the highest average review rating?
-- Simple quality ranking — flags products that are consistently well
-- reviewed, independent of how often they're bought.
SELECT TOP 5
       item_purchased,
       ROUND(CAST(AVG(review_rating) AS DECIMAL(10,2)), 2) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;
 
 
-- Q7. Which 5 products have the highest percentage of purchases made with
-- a discount applied?
-- A high discount rate on a product can mean it's price-sensitive demand,
-- overstocked, or being used as a loss-leader — worth flagging for
-- margin review.
SELECT TOP 5
       item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;
 
 
-- Q8. What are the top 3 most purchased products within each category?
-- Ranks products inside their own category (rather than globally) using
-- ROW_NUMBER() with PARTITION BY, so a category with fewer total sales
-- still gets its own top performers identified rather than being drowned
-- out by a larger category.
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3;
 
 
-- Q9. Which category generates the most revenue in each season,
-- and how does total revenue vary by season overall?
-- Retail demand is seasonal — this checks whether one category dominates
-- consistently across all seasons, or whether different categories lead
-- in different seasons (which would argue for season-specific merchandising
-- or promotion planning).
WITH seasonal_category_revenue AS (
    SELECT season,
           category,
           SUM(purchase_amount_usd) AS category_revenue,
           RANK() OVER (PARTITION BY season ORDER BY SUM(purchase_amount_usd) DESC) AS category_rank
    FROM customer
    GROUP BY season, category
)
SELECT season,
       category        AS top_category,
       category_revenue
FROM seasonal_category_revenue
WHERE category_rank = 1
ORDER BY category_revenue DESC;
 
 
/* ============================================================================
   SECTION 3: CUSTOMER SEGMENTATION & LOYALTY
   ============================================================================
   These queries group customers into behavioral segments and compare
   spend and subscription patterns across them.
*/
 
-- Q10. Do subscribed customers spend more? Compare average spend and total
-- revenue between subscribers and non-subscribers.
-- Directly tests whether the subscription program correlates with higher-
-- value customers — relevant for deciding whether to invest further in
-- subscription growth.
SELECT subscription_status,
       COUNT(customer_id)                   AS total_customers,
       ROUND(AVG(purchase_amount_usd), 2)    AS avg_spend,
       ROUND(SUM(purchase_amount_usd), 2)    AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;
 
 
-- Q11. Segment customers into New, Returning, and Loyal based on their
-- total number of previous purchases, and show the count of each segment.
-- NOTE: previous_purchases = 0 is treated as "New" (first purchase, no
-- prior history). This closes a gap in the original segment logic, where
-- a 0-purchase customer would otherwise have fallen through to "Loyal"
-- by default via the ELSE clause — clearly not the intent.
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 0             THEN 'New'
               WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS [Number of Customers]
FROM customer_type
GROUP BY customer_segment;
 
 
-- Q12. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
-- Checks whether purchase history and subscription status move together —
-- if repeat buyers are disproportionately non-subscribers, that's a
-- targeted upsell opportunity.
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
 
 
-- Q13. How does purchase frequency relate to spend — do more
-- frequent buyers spend less per transaction but more in total history?
-- Uses the purchase_frequency_days feature (numeric days-between-purchases,
-- engineered from the original text labels like "Weekly"/"Annually") to
-- test a common retail hypothesis: frequent buyers often have smaller
-- basket sizes per visit but higher lifetime value overall.
SELECT frequency_of_purchases,
       purchase_frequency_days,
       COUNT(*)                              AS customer_count,
       ROUND(AVG(purchase_amount_usd), 2)     AS avg_purchase_amount,
       ROUND(AVG(previous_purchases), 1)      AS avg_previous_purchases
FROM customer
GROUP BY frequency_of_purchases, purchase_frequency_days
ORDER BY purchase_frequency_days;
 
 
/* ============================================================================
   SECTION 4: BEHAVIORAL & CROSS-FACTOR ANALYSIS
   ============================================================================
   These queries cross-reference behavioral fields (discounts, payment
   method) against satisfaction and spend to surface patterns that aren't
   obvious from a single-column view.
*/
 
-- Q14. Is there a relationship between discount usage and
-- review rating?
-- Tests whether getting a discount changes how customers rate their
-- purchase — e.g., do discounted buyers rate lower (bargain-hunting,
-- lower expectations of the item itself) or about the same as full-price
-- buyers (rating driven by the product, not the price paid)?
SELECT discount_applied,
       COUNT(*)                          AS total_purchases,
       ROUND(AVG(review_rating), 2)      AS avg_review_rating
FROM customer
GROUP BY discount_applied;
 
 
-- Q15. Which payment method is associated with the highest
-- average purchase amount?
-- Payment method can proxy for customer type — e.g., customers who save
-- card details or use certain digital wallets may skew toward higher or
-- lower basket sizes. Useful context for checkout flow and payment
-- partnership decisions.
SELECT payment_method,
       COUNT(*)                              AS total_transactions,
       ROUND(AVG(purchase_amount_usd), 2)     AS avg_purchase_amount
FROM customer
GROUP BY payment_method
ORDER BY avg_purchase_amount DESC;
